[package]
name = "degen-lang"
version = "0.1.0"
authors = ["Orhan Yigit Yazicilar", "Aldiyar Ablyazov", "Alexandre Guerville", "Tamim Azmain"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
